//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DELL\\SQLEXPRESS;Initial Catalog=QuanLyKhachSan;Integrated Security=Tr" +
            "ue;TrustServerCertificate=True")]
        public string QuanLyKhachSanConnectionString {
            get {
                return ((string)(this["QuanLyKhachSanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DELL\\SQLEXPRESS;Initial Catalog=QuanLyKhachSan;Integrated Security=Tr" +
            "ue;Encrypt=True;TrustServerCertificate=True")]
        public string QuanLyKhachSanConnectionString1 {
            get {
                return ((string)(this["QuanLyKhachSanConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=3.10.179.51;Initial Catalog=QuanLyKhachSan;User ID=admin;Password=Lam" +
            "123;Encrypt=True;TrustServerCertificate=True")]
        public string QuanLyKhachSanConnectionString2 {
            get {
                return ((string)(this["QuanLyKhachSanConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=34.41.188.38;Initial Catalog=QuanLyKhachSan;User ID=phonglam;Password" +
            "=123456;Encrypt=True;TrustServerCertificate=True")]
        public string QuanLyKhachSanConnectionString3 {
            get {
                return ((string)(this["QuanLyKhachSanConnectionString3"]));
            }
        }
    }
}
